package sap_api_input_reader

import (
	"sap-api-integrations-maintenance-item-creates/SAP_API_Caller/requests"
)

func (sdc *SDC) ConvertToItem() *requests.Item {
	data := sdc.MaintenanceItem
	return &requests.Item{
		MaintenanceItem:              data.MaintenanceItem,
		MaintenanceItemDescription:   data.MaintenanceItemDescription,
		MaintenanceStrategy:          data.MaintenanceStrategy,
		MaintenancePlanCategory:      data.MaintenancePlanCategory,
		MaintenancePlanCallObject:    data.MaintenancePlanCallObject,
		MaintenancePlan:              data.MaintenancePlan,
		MaintenancePlanItemPosition:  data.MaintenancePlanItemPosition,
		MaintenanceItemObjectList:    data.MaintenanceItemObjectList,
		FunctionalLocationLabelName:  data.FunctionalLocationLabelName,
		Equipment:                    data.Equipment,
		Assembly:                     data.Assembly,
		AdditionalDeviceData:         data.AdditionalDeviceData,
		TaskListType:                 data.TaskListType,
		TaskListGroup:                data.TaskListGroup,
		TaskListGroupCounter:         data.TaskListGroupCounter,
		OperationSystemCondition:     data.OperationSystemCondition,
		NumberOfTaskListExecutions:   data.NumberOfTaskListExecutions,
		MaintNotifTskIsAutomlyDtmnd:  data.MaintNotifTskIsAutomlyDtmnd,
		MaintenancePlanningPlant:     data.MaintenancePlanningPlant,
		MaintenancePlannerGroup:      data.MaintenancePlannerGroup,
		MaintenanceOrderType:         data.MaintenanceOrderType,
		NotificationType:             data.NotificationType,
		MaintenanceActivityType:      data.MaintenanceActivityType,
		MainWorkCenter:               data.MainWorkCenter,
		MainWorkCenterPlant:          data.MainWorkCenterPlant,
		MaintPriority:                data.MaintPriority,
		MaintPriorityType:            data.MaintPriorityType,
		BusinessArea:                 data.BusinessArea,
		ImmediateReleaseIsBlocked:    data.ImmediateReleaseIsBlocked,
		Material:                     data.Material,
		SerialNumber:                 data.SerialNumber,
		ServiceDocumentType:          data.ServiceDocumentType,
		ServiceContract:              data.ServiceContract,
		ServiceContractItem:          data.ServiceContractItem,
		ServiceOrderTemplate:         data.ServiceOrderTemplate,
		ServiceDocumentPriority:      data.ServiceDocumentPriority,
		Product:                      data.Product,
		MaintenancePlant:             data.MaintenancePlant,
		AssetLocation:                data.AssetLocation,
		AssetRoom:                    data.AssetRoom,
		PlantSection:                 data.PlantSection,
		WorkCenter:                   data.WorkCenter,
		ABCIndicator:                 data.ABCIndicator,
		MaintObjectFreeDefinedAttrib: data.MaintObjectFreeDefinedAttrib,
		CompanyCode:                  data.CompanyCode,
		MasterFixedAsset:             data.MasterFixedAsset,
		FixedAsset:                   data.FixedAsset,
		LocAcctAssgmtBusinessArea:    data.LocAcctAssgmtBusinessArea,
		CostCenter:                   data.CostCenter,
		ControllingArea:              data.ControllingArea,
		WBSElement:                   data.WBSElement,
		SettlementOrder:              data.CycleSetSequence,
		CycleSetSequence:             data.CycleSetSequence,
		StandingOrderNumber:          data.StandingOrderNumber,
		CreationDate:                 data.CreationDate,
		LastChangeDate:               data.LastChangeDate,
		LastChangeDateTime:           data.LastChangeDateTime,
	}
}
